### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by TalfanBarnie** [dawhite/APTK#2]
Hello,

I'm writing up some work where we used APTK, and I was wondering if you have a preferred way of having it cited or acknowledged in academic journal articles? 

Many thanks,

Talfan

**Comment by dawhite** [comment]
Thank you for asking. I'll generate some language today and post it here.

**Comment by dawhite** [comment]
This is a PNAS-formatted citation you can use:

Devin A. White (2016) APTK: The ASTER Preprocessing Toolkit, Version 1.0.3, https://github.com/dawhite/APTK.

**Comment by TalfanBarnie** [comment]
Great, many thanks!

Talfan
