### ISSUE TITLE
Error converting AST_08 files

### ISSUE THREAD

**Issue by TalfanBarnie** [dawhite/APTK#3]
Hello,

We''re trying to write an IDL script to build RPCs for a large number of AST_08 / AST_L1A images, however the script fails and no output files are produced. When we test individual AST_08 / AST_L1A image pairs using the GUI, we get the following error:

"Supplied HDF does not contain relevant information"

The options used were:

input file : AST_08_00301012006031537_20180716081511_37599.hdf
output path: C\users\name\output\
Align Bands for level 1A: No (greyed out)
DEM file: none (greyed out)
Build RPCs for level 1B or level 2: Yes
L1A File: AST_L1A_00301012006031537_20180717133220_9141.hdf
Resampling: Bilinear (greyed out)

The files were ordered using NASA Earth Data search, and we're using ENVI 5.4. Do you have ideas about what we might be doing wrong?

Many thanks for your help!

Talfan

**Comment by dawhite** [comment]
I just double-checked the code and that error message only shows up under two possible conditions: (1) one of the supplied files is not in HDF-EOS format or (2) one of the files is not reporting that it contains swath datasets. I'll check the files you mention above and let you know what I find out.

**Comment by dawhite** [comment]
I ordered the same data from NASA EarthData Search and ran it through APTK 1.1.0. I was not able to reproduce that error message, which makes me think that one of the two files you have were corrupted during download. That is not uncommon if you are doing a bulk download. I did discover a metadata parsing bug that would prevent the file from being processed, though. I'm not sure if it impacts just this particular AST_08 file, but I went ahead and put a more general fix in place. The file processes fine now. I'll get a new release posted later today or tomorrow. Also, you can capture error messages in batch mode by using the 'msg' keyword. I need to fix that in the user guide. If you set that keyword to a variable, it will contain any error message that comes back, which you can log or print as needed.

**Comment by TalfanBarnie** [comment]
Great, many thanks for looking into it for us! We'll try re-downloading the files and processing them with the new script, and get back to you.

**Comment by dawhite** [comment]
I just pushed a new version of APTK (v1.1.1) that addresses this issue. Please download it from the Releases page and let me know if it works for you.

**Comment by TalfanBarnie** [comment]
Thanks again! I'm afraid we won't get to look at the data again until Tuesday 18th - I'll let you know how it goes then.

**Comment by TalfanBarnie** [comment]
Just to keep you updated, unfortunately we've just lost access to our ENVI license - we're trying to get another, but it may take a while ... sorry to keep you waiting!

**Comment by TalfanBarnie** [comment]
We've been able to test the same file with your new version of APTK (V1.1.1) and it now works. Thanks again for your help!

**Comment by dawhite** [comment]
Glad to hear that it's working for you!
