### ISSUE TITLE
FLAASH - Problem

### ISSUE THREAD

**Issue by charanchaganti93** [dawhite/APTK#4]
I have downloaded L1B data for March 2002, crosstalk correction was applied using crosstalk 3 after which I applied FLAASH. After the atmospheric correction has been applied, Band 9 shows high value which should not be the case. Please suggest

Attaching the image for your reference.

![plot](https://user-images.githubusercontent.com/71376959/106560686-6d906980-654d-11eb-83f9-22007233046d.jpg)

**Comment by dawhite** [comment]
I recommend contacting technical support for L3Harris Geospatial: https://www.l3harrisgeospatial.com/Support/Technical-Support
